// Package install renders and places the artifacts a bare-metal host
// needs to serve a model: the systemd unit and the manifest it names
// (specs/020-bare-metal-packaging.md).
//
// The unit is generated from the manifest rather than hand-written. It
// is almost entirely derivable — the model's name, the manifest it
// serves, the binary that serves it — so hand-writing it would create a
// second place for that information to be wrong. What is *not*
// derivable is where things live on a given host, and that is what
// Options carries.
package install

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/latere-ai/llmops/internal/manifest"
)

// Defaults for a host that has no opinion. ConfigDir and UnitDir follow
// the usual Linux placements; BinPath matches what specs/020's unit
// names and what deploycheck asserts.
const (
	DefaultBinPath   = "/usr/local/bin/llmops"
	DefaultConfigDir = "/etc/llmops"
	DefaultUnitDir   = "/etc/systemd/system"

	// DefaultStartTimeout is generous on purpose. A 0.6B model took
	// 325 s from launch to /health on the GB10 class (specs/019), most
	// of it weight load and engine warmup, and a 27B model is far
	// slower. systemd's 90 s default would kill the service mid-load
	// and then keep killing it, which reads as a crash loop rather than
	// a timeout.
	DefaultStartTimeout = "30min"
)

// Options are the host-specific parts of an install.
type Options struct {
	BinPath   string // installed llmops binary
	ConfigDir string // where the manifest is placed
	UnitDir   string // where the unit is written
	CacheRoot string // weights root passed to serve; empty omits the flag
	User      string // run as this user; empty means systemd's default

	// Reload tells systemd to re-read units after the unit changed.
	// Defaults to `systemctl daemon-reload`.
	//
	// It is injectable because reloading is the one step that touches
	// the machine rather than a directory: a test writing to a temp
	// prefix has no business reloading the host's systemd, and on a CI
	// runner the attempt fails with "Interactive authentication
	// required" rather than being absent.
	Reload func(log io.Writer) error
}

func (o *Options) defaults() {
	if o.BinPath == "" {
		o.BinPath = DefaultBinPath
	}
	if o.ConfigDir == "" {
		o.ConfigDir = DefaultConfigDir
	}
	if o.UnitDir == "" {
		o.UnitDir = DefaultUnitDir
	}
}

// ManifestPath is where this model's manifest lands on the host. It is
// also what the unit's --manifest names, so the two cannot disagree.
func (o Options) ManifestPath(m *manifest.Manifest) string {
	o.defaults()
	return filepath.Join(o.ConfigDir, m.Name+".yaml")
}

// UnitPath is where this model's unit is written.
func (o Options) UnitPath(m *manifest.Manifest) string {
	o.defaults()
	return filepath.Join(o.UnitDir, UnitName(m))
}

// UnitName is the unit's filename, matching the artifact deploycheck
// expects at deploy/<name>/<name>.service.
func UnitName(m *manifest.Manifest) string { return m.Name + ".service" }

// Unit renders the systemd unit for a model.
func Unit(m *manifest.Manifest, o Options) string {
	o.defaults()
	exec := o.BinPath + " serve --manifest " + o.ManifestPath(m)
	if o.CacheRoot != "" {
		exec += " --cache-root " + o.CacheRoot
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `llmops install` from models/%s.yaml — do not edit.\n", m.Name)
	fmt.Fprintf(&b, "# Regenerate after changing the manifest; specs/020.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=llmops %s (%s on %dx%s)\n", m.Name, m.Runtime, m.GPU.Count, m.GPU.Type)
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")

	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	if o.User != "" {
		fmt.Fprintf(&b, "User=%s\n", o.User)
	}
	fmt.Fprintf(&b, "ExecStart=%s\n", exec)
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=10\n")
	// See DefaultStartTimeout: weight load on this class outruns
	// systemd's default and the failure looks like a crash loop.
	fmt.Fprintf(&b, "TimeoutStartSec=%s\n", DefaultStartTimeout)
	b.WriteString("KillSignal=SIGTERM\n")
	// The engine is a child process; serve reaps it on SIGTERM, but a
	// stuck engine must not hold the unit open forever.
	b.WriteString("TimeoutStopSec=2min\n\n")

	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// Result reports what an install changed, so a second run over an
// unchanged manifest can say "nothing" rather than implying work.
type Result struct {
	ManifestPath    string
	UnitPath        string
	ManifestChanged bool
	UnitChanged     bool
	DaemonReloaded  bool
}

// Run places the manifest and unit for a bare-metal model.
//
// It is idempotent by content: identical files are left alone, so a
// repeated install neither rewrites nor duplicates, and systemd is only
// reloaded when the unit actually changed.
func Run(m *manifest.Manifest, srcManifest string, o Options, log io.Writer) (*Result, error) {
	o.defaults()
	if m.DeployMode() != manifest.DeployBareMetal {
		return nil, fmt.Errorf("%s is deploy: %s; install writes a systemd unit and only applies to bare-metal",
			m.Name, m.DeployMode())
	}
	data, err := os.ReadFile(srcManifest)
	if err != nil {
		return nil, err
	}

	res := &Result{ManifestPath: o.ManifestPath(m), UnitPath: o.UnitPath(m)}
	res.ManifestChanged, err = writeIfChanged(res.ManifestPath, data, 0o644)
	if err != nil {
		return nil, err
	}
	res.UnitChanged, err = writeIfChanged(res.UnitPath, []byte(Unit(m, o)), 0o644)
	if err != nil {
		return nil, err
	}

	fmt.Fprintf(log, "manifest %s (%s)\n", res.ManifestPath, changed(res.ManifestChanged))
	fmt.Fprintf(log, "unit     %s (%s)\n", res.UnitPath, changed(res.UnitChanged))

	if res.UnitChanged {
		reload := o.Reload
		if reload == nil {
			reload = daemonReload
		}
		// A reload failure is reported, not fatal: the unit and manifest
		// are already correct on disk, and the operator can reload
		// themselves. Failing here would turn a complete install into a
		// non-zero exit — and an unprivileged install into a staging
		// directory is a legitimate use.
		if err := reload(log); err != nil {
			fmt.Fprintf(log, "warning: %v\n", err)
			fmt.Fprintf(log, "the unit is written; run `systemctl daemon-reload` to pick it up\n")
		} else {
			res.DaemonReloaded = true
		}
	}
	return res, nil
}

func changed(b bool) string {
	if b {
		return "written"
	}
	return "unchanged"
}

// writeIfChanged writes only when the content differs, so an install
// that changes nothing leaves mtimes alone and systemd untouched.
func writeIfChanged(path string, data []byte, mode os.FileMode) (bool, error) {
	if old, err := os.ReadFile(path); err == nil && string(old) == string(data) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(path, data, mode)
}

// daemonReload asks systemd to re-read units. A host without systemctl
// is not an error: rendering the files is still useful on a machine
// that is staging them for another.
func daemonReload(log io.Writer) error {
	path, err := exec.LookPath("systemctl")
	if err != nil {
		fmt.Fprintln(log, "systemctl not found; skipping daemon-reload")
		return nil
	}
	if out, err := exec.Command(path, "daemon-reload").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl daemon-reload: %w: %s", err, strings.TrimSpace(string(out)))
	}
	fmt.Fprintln(log, "systemctl daemon-reload: ok")
	return nil
}
